a=int(input("a"))
b=int(input('b'))
print('add is',a+b)
print('remainder for a/b',a%b)
print(type(a))
print("a is greater than b is ",a>b)
print("the average of two no is",(a+b)/2)
print("square of a is",a**2)
print("square of a is",a*a)